import type { Metadata } from "next";
import { Quicksand, Comfortaa } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ChatAssistant from "@/components/ChatAssistant";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${quicksand.variable} ${comfortaa.variable}  antialiased`}
      >
        <div className="font-serif">
          <Navbar />

          {children}
          <Footer />
          <ChatAssistant />
        </div>
      </body>
    </html>
  );
}
